# This is an example config file showing all the config options
# in general the presence of, or lack of, a config section should enable or disable the plugin.
[ tool.giles-dev ]

  [ tool.giles-dev.circleci_artifacts.sphinx ]
    url = "html/index.html"
    message = "This is the documentation"

  [ tool.giles-dev.circleci_artifacts.random ]
    url = "parrot.gif"
    message = "This is a parrot"
